version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: hostel_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: HostelManagement
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
      - ./commands.sql:/docker-entrypoint-initdb.d/commands.sql
    ports:
      - "4121:3306"

  app:
    build: .
    container_name: hostel_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: HostelManagement
      DB_USER: user
      DB_PASSWORD: user_password
    volumes:
      - .:/app
    command: ["/bin/bash", "-c", "./wait-for-db.sh db:3306 -- python App.py & sleep 5 && streamlit run main.py"]
    ports:
      - "8000:8000"

volumes:
  db_data:
